// <auto-generated />
using System;
using EnterpriseGovernance.Adapters.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnterpriseGovernance.Adapters.Database.Migrations
{
    [DbContext(typeof(GovernanceDbContext))]
    partial class GovernanceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.16");

            modelBuilder.Entity("EnterpriseGovernance.Core.Domain.ContentTypeDefinition", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActiveInTenant")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TenantAuditResultScanDateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantAuditResultScanDateTime");

                    b.ToTable("ContentTypes");
                });

            modelBuilder.Entity("EnterpriseGovernance.Core.Domain.FieldDefinition", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentTypeDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InternalName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSealed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("TenantAuditResultScanDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentTypeDefinitionId");

                    b.HasIndex("TenantAuditResultScanDateTime");

                    b.ToTable("Fields");
                });

            modelBuilder.Entity("EnterpriseGovernance.Core.Domain.TenantAuditResult", b =>
                {
                    b.Property<DateTime>("ScanDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ScanDateTime");

                    b.ToTable("AuditResults");
                });

            modelBuilder.Entity("EnterpriseGovernance.Core.Domain.ContentTypeDefinition", b =>
                {
                    b.HasOne("EnterpriseGovernance.Core.Domain.TenantAuditResult", null)
                        .WithMany("DetectedContentTypes")
                        .HasForeignKey("TenantAuditResultScanDateTime")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EnterpriseGovernance.Core.Domain.FieldDefinition", b =>
                {
                    b.HasOne("EnterpriseGovernance.Core.Domain.ContentTypeDefinition", null)
                        .WithMany("Fields")
                        .HasForeignKey("ContentTypeDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EnterpriseGovernance.Core.Domain.TenantAuditResult", null)
                        .WithMany("DetectedGlobalFields")
                        .HasForeignKey("TenantAuditResultScanDateTime")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EnterpriseGovernance.Core.Domain.ContentTypeDefinition", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("EnterpriseGovernance.Core.Domain.TenantAuditResult", b =>
                {
                    b.Navigation("DetectedContentTypes");

                    b.Navigation("DetectedGlobalFields");
                });
#pragma warning restore 612, 618
        }
    }
}
